name: thinking_board
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  fast_immutable_collections: ^7.2.1
  build_config: ^1.0.0
  json_serializable: ^6.1.5
  import_sorter: ^4.6.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  freezed: ^1.1.1
  build_runner: ^2.1.8
  analyzer: ^3.3.1

